### ISSUE TITLE
Build failing since last changes.

### ISSUE THREAD

**Issue by pierremanceaux** [nfroidure/gulp-svg2ttf#9]
First of all, thanks for this amazing tool that I am using since years <3

Quickly reporting an issue I am facing since last changes made on gulp-svg2ttf (maybe some dependencies?). I will fallback for now, but here is the error:
```
[16:53:08] gulp-svgicons2svgfont: Font created
Number of icons:  61

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at Transform.svg2ttfTransformStream [as _transform] (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/gulp-svg2ttf/src/index.js:87:32)
    at Transform._read (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at Transform._write (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Transform.Writable.write (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Duplexer.ondata (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:77:13)
    at Duplexer.emit (events.js:169:7)
    at addChunk (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Duplexer.Readable.push (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at Duplexer._pushAll (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/plexer/src/index.js:105:31)
    at PassThrough.<anonymous> (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/plexer/src/index.js:82:13)
    at emitNone (events.js:67:13)
    at PassThrough.emit (events.js:166:7)
    at emitReadable_ (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:497:10)
    at emitReadable (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:491:65)
    at addChunk (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:291:29)
    at readableAddChunk (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at PassThrough.Readable.push (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at PassThrough.Transform.push (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at SVGIcons2SVGFontStream.<anonymous> (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/gulp-svgicons2svgfont/src/index.js:103:24)
    at emitNone (events.js:72:20)
    at SVGIcons2SVGFontStream.emit (events.js:166:7)
    at endReadableNT (/Users/pierre/dev/thermondo-frontend-wagtail/client/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at nextTickCallbackWith2Args (node.js:442:9)
```

Here my settings:
```
fontName: 't-website-icons',
appendUnicode: false,
startUnicode: 0xE001,
normalize: true,
fontHeight: 100,
descent: 18,
formats: ['svg', 'ttf', 'eot', 'woff'],
timestamp: runTimestamp,
```

**Comment by pierremanceaux** [comment]
False positive, I had an issue on heroku, needed to clear cache and install last version of node (6.11.1 so far). This fixed the problem 👍
